cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
] 

firstproject/urls.py
from django.urls import path
from . import views

app_name = 'firstproject'

urlpatterns = [
    path('info', views.info_view, name='info_view'),
    path('', views.product_list, name='product_list'),
    path('create/', views.product_create, name='product_create'),
    path('register/', views.register, name='register'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('<int:id>/<slug:slug>/update/', views.product_update, name='product_update'),
    path('<int:id>/<slug:slug>/delete/', views.product_delete, name='product_delete'),
    path('api/products/', views.ProductListAPIView.as_view(), name='api_product_list'),
    path('api/products/<int:pk>/', views.ProductDetailAPIView.as_view(), name='api_product_detail'),
    path('api/categories/', views.CategoryListAPIView.as_view(), name='api_category_list'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('firstproject.urls')),
    path('account/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from firstproject.models import Product
from .cart import Cart
from firstproject.forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True
        })
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Ваша корзина
{% endblock %}

{% block content %}
    <h1>Ваша корзина</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Изображение</th>
                <th>Товар</th>
                <th>Количество</th>
                <th>Удалить</th>
                <th>Цена за единицу</th>
                <th>Итого</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.override }}
                                <input type="submit" value="Обновить">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td>
                            <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                <input type="submit" value="Удалить">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td>₽{{ item.price }}</td>
                        <td>₽{{ item.total_price }}</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Итого</td>
                <td colspan="4"></td>
                <td class="num">₽{{ cart.get_total_price }}</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "firstproject:product_list" %}" class="button light">Продолжить покупки</a>
        <a href="#" class="button">Оформить заказ</a>
    </p>
{% endblock %} 